# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog02', '0002_auto_20170503_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='category',
            new_name='post',
        ),
    ]
